services:
  ################################################
  #                Transport                     #
  ################################################
  notification.transport.email:
    class: Sokil\NotificationBundle\Transport\EmailTransport
    tags:
      - {name: 'notification.transport', transportName: 'email'}
    arguments:
      - '@mailer'
      - ''
      - ''

  notification.transport_provider:
    class: Sokil\NotificationBundle\TransportProvider

  ################################################
  #                Schema                        #
  ################################################
  notification.schema_provider:
    class: Sokil\NotificationBundle\Schema\ConfigurationProvider
    arguments:
      - {}

  ################################################
  #                Message                       #
  ################################################
  notification.message_builder_collection:
    class: Sokil\NotificationBundle\MessageBuilder\BuilderCollection
    tags:
      - {name: 'notification.message_builder_collection', collectionName: 'default'}
